#include QMK_KEYBOARD_H
#include "config.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

bool is_alt_tab_active = false; // ADD this near the begining of keymap.c
uint16_t alt_tab_timer = 0;     // we will be using them soon.

bool is_windows = false;

enum custom_keycodes {          // Make sure have the awesome keycode ready
  ALT_TAB = SAFE_RANGE,
  ALT_GRAVE,
  TOGGLE_WINDOWS,
  SSHOT
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, /**/ LSFT_T(KC_A), LT(5,KC_S), LT(1,KC_D), LT(3,KC_F), KC_G, KC_H, LT(4,KC_J), LT(2,KC_K), LT(6,KC_L), LSFT_T(KC_SCLN), SGUI_T(KC_Z), /**/ LCTL_T(KC_X), LALT_T(KC_C), KC_V, LCAG_T(KC_B), KC_N, KC_M, LALT_T(KC_COMM), LCTL_T(KC_DOT), LCAG_T(KC_SLSH), /**/ LT(7,KC_ESC), LGUI_T(KC_SPC), RGUI_T(KC_BSPC), LT(7,KC_ENT)),
	[1] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSLS, KC_AMPR, KC_ASTR, KC_GRV, KC_TRNS, /**/ LSFT_T(KC_ESC), KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_QUOT, KC_DLR, KC_PERC, KC_CIRC, RSFT_T(KC_QUOT), KC_TRNS, /**/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SLSH, KC_EXLM, KC_AT, KC_HASH, KC_TRNS, /**/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT_split_3x5_2(KC_PAST, KC_7, KC_8, KC_9, KC_PMNS, KC_PSLS, KC_PGUP, KC_NO, KC_NO, KC_NO, /**/ KC_0, KC_4, KC_5, KC_6, KC_PPLS, KC_PAST, KC_HOME, KC_NO, KC_END, KC_NO, /**/ KC_PDOT, KC_1, KC_2, KC_3, KC_PEQL, KC_PENT, KC_PGDN, KC_RALT, KC_RGUI, KC_RCTL, KC_VOLD, KC_MPLY, KC_TRNS, KC_VOLU),
	[3] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_QUOT, /**/ KC_TRNS, KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, KC_TRNS, KC_HASH, KC_TILD, KC_SLSH, /**/ KC_DQUO, KC_DLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_BSLS, KC_GRV, KC_TRNS, RGB_RMOD, KC_TRNS, KC_TRNS, RGB_MOD),
	[4] = LAYOUT_split_3x5_2(KC_TRNS, KC_COLN, KC_LT, KC_GT, KC_SCLN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, /**/ KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT, KC_TRNS, KC_NO, KC_MINS, KC_PLUS, KC_PERC, /**/ KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_EQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_TRNS, KC_TRNS, KC_VOLU),
	[5] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, /**/ KC_TRNS, KC_NO, LCTL(KC_LALT), KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, /**/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[6] = LAYOUT_split_3x5_2(KC_BTN3, KC_BTN1, KC_WH_U, KC_BTN2, KC_ACL0, DM_PLY1, DM_REC1, DM_RSTP, KC_TRNS, KC_TRNS, /**/ KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_ACL1, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, /**/ KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_R, KC_ACL2, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[7] = LAYOUT_split_3x5_2(TOGGLE_WINDOWS, KC_TRNS, KC_COLN, KC_ESC, KC_INS, DM_PLY1, DM_REC1, DM_RSTP, SSHOT, /**/ KC_HOME, KC_TRNS, KC_PERC, KC_SLSH, KC_ENT, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, /**/ KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRV, KC_TAB, ALT_TAB, ALT_GRAVE, RALT_T(KC_COMM), TG(8), RESET, KC_DEL, KC_TRNS, KC_NO, KC_GRV),
	[8] = LAYOUT_split_3x5_2(KC_GRV, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, /*2*/ KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L,/*3*/ KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, TG(8), /*4*/ KC_LSFT, KC_SPC, KC_BSPC, KC_ENT)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) { // This will do most of the grunt work with the keycodes.
    case ALT_TAB:
      if (record->event.pressed) {
        if (!is_alt_tab_active) {
          is_alt_tab_active = true;
          register_code(is_windows ? KC_LALT : KC_LGUI);
        }
        alt_tab_timer = timer_read();
        register_code(KC_TAB);
      } else {
        unregister_code(KC_TAB);
      }
      break;
    case ALT_GRAVE:
      if (record->event.pressed) {
        register_code(is_windows ? KC_LALT : KC_LGUI);
        register_code(KC_GRV);
      } else {
        unregister_code(KC_GRV);
        unregister_code(is_windows ? KC_LALT : KC_LGUI);
      }
      break;
    case TOGGLE_WINDOWS:
      process_magic(MAGIC_TOGGLE_CTL_GUI, record);
      if (record->event.pressed) {
        is_windows = !is_windows;
      }
      break;
    case SSHOT:
      if (is_windows) { break; }
      if (record->event.pressed) {
        register_code(KC_LGUI);
        register_code(KC_LCTL);
        register_code(KC_LSFT);
        register_code(KC_4);
      } else {
        unregister_code(KC_4);
        unregister_code(KC_LGUI);
        unregister_code(KC_LCTL);
        unregister_code(KC_LSFT);
      }
      break;
  }
  return true;
}

void matrix_scan_user(void) { // The very important timer.
  if (is_alt_tab_active) {
    if (timer_elapsed(alt_tab_timer) > 1000) {
      unregister_code(is_windows ? KC_LALT : KC_LGUI);
      is_alt_tab_active = false;
    }
  }
}
