// 1000hz Polling Rate
#define USB_POLLING_INTERVAL_MS 4
#define QMK_KEYS_PER_SCAN 12
// #define MASTER_RIGHT 1
#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_SINGLE_REPORT
#define DEVICE_VER 0x0010
#define PRODUCT "Lily58"
#define MANUFACTURER "Flower"
#define SPLIT_HAND_PIN D1